### PR TITLE
Update versions of dependencies

### PR DESCRIPTION
**Pull request by sazzad16**

### CODE REVIEW

**Comment by sazzad16** [comment]
@marcosnils @gkorland I think we should update our dependencies. I'm not 100% about `commons-pool2` though.

**Comment by gkorland** [comment]
@sazzad16 I think we were waiting for commons-pool2 2.6.1?

**Comment by sazzad16** [comment]
@gkorland Yes, we are waiting for commons-pool2 2.6.1. That's I've expressed my concern over it. However, we're waiting for quite some time and 2.6.0 is the latest one we can use right now.

Keeping commons-pool2 aside, I think we should consider updating other dependencies. Our log dependencies are old and JUnit is very old.

**Comment by gkorland** [comment]
@sazzad16 the only thing is that I don't think we should have it in 3.0.2 but in 3.1.0

**Comment by sazzad16** [comment]
@gkorland Okay. done.

**Comment by marcosnils** [comment]
LGTM!.

**Pull request merged**
