### PR TITLE
Pexpire at

### PR DESCRIPTION
**Pull request by Tavio**
Adding the pexpireAt command to interfaces that missed it (and their corresponding implementations). I'm not implementing the pexpire command here because it is already present in a recent PR by @nykolaslima.

### CODE REVIEW

**Comment by nykolaslima** [comment]
LGTM. What do you think @HeartSaVioR @marcosnils?

**Comment by HeartSaVioR** [comment]
LGTM, too.

**Comment by HeartSaVioR** [comment]
It adds missed spots so I labeled it with 2.6.3.
Seems like if we release minor version faster, I can label this to 2.7.0 too.

**Comment by nykolaslima** [comment]
@marcosnils @xetorthio Do you guys have any consideration on this? Can we merge it?

**Comment by xetorthio** [comment]
The implementation is fine. But it is missing tests, right?

**Comment by nykolaslima** [comment]
As @HeartSaVioR commented on https://github.com/xetorthio/jedis/pull/869, we don't have tests for `ShardedJedis` so I think it's fine. After all, it only delegates to `Jedis` that is already tested.

**Comment by HeartSaVioR** [comment]
Yes, it is not only this PR's issue. 
We need to place 'under construction' and do a numerous changes in order to achieve.
So unless we decide to go on, I think it's good to merge, at least 2.x version.

**Comment by marcosnils** [comment]
Upmerged to 2.7 and 2.6

**Pull request merged**
