### PR TITLE
Moved scan command into MultiKey... interface

### PR DESCRIPTION
**Pull request by sazzad16**

### CODE REVIEW

**Comment by marcosnils** [comment]
hey @sazzad16 . Thx for your contributions!. I guess this PR has changes that shouldn't be in here right?

Like some guideline removas and copyright changes.

**Comment by sazzad16** [comment]
@marcosnils I needed to create a build with some pending changes. This is happened when I was trying to merge into common place.

I will fix these as soon as I can :)

**Comment by HeartSaVioR** [comment]
LGTM. TBH, I guess it breaks backward compatibility, but I would rather not thinking someone uses JedisCluster with interface.
@mp911de Could you please check there's any issues on Spring Data Redis if we adopt the change?
@marcosnils Please review this as well.

**Comment by HeartSaVioR** [comment]
This is actually a bugfix, not improvement. So I just marked target version as bugfix version. Please let me know if someone doesn't agree.

**Comment by mp911de** [comment]
Thanks for the ping. This change doesn't break Spring Data Redis as we don't use `SCAN` in cluster yet and we directly use `JedisCluster`/`BinaryJedisCluster`.

For anybody using the interfaces directly, it's a breaking change which shouldn't happen in a patch release at all. Wouldn't it be possible to deprecate `scan(…)` in `BinaryJedisClusterCommands` with a hint (`@see …`) so you can remove the method in 3.0?

**Comment by marcosnils** [comment]
> This is actually a bugfix, not improvement. So I just marked target version as bugfix version. Please let me know if someone doesn't agree.

But it still breaks backwards compatibility. I'd vote for marking it as *deprecated* and push the change to 3.0

@HeartSaVioR @mp911de @sazzad16 ?

**Comment by mp911de** [comment]
Introducing the method on `MultiKeyBinaryJedisClusterCommands` and deprecating the old one doesn't for 2.10 would be a nice move and allow users to adapt the new code before 3.0.

**Comment by sazzad16** [comment]
@marcosnils @mp911de agreed!

**Comment by sazzad16** [comment]
PR for 2.10 #1668

**Comment by sazzad16** [comment]
Merged into master.

**Pull request merged**
