### PR TITLE
Added support for georadius_ro, georadiusbymember_ro commands

### PR DESCRIPTION
**Pull request by s-sathish**

### CODE REVIEW

**Comment by marcosnils** [comment]
> I think ReadOnly instead of _ro makes the code and usage more readable. @marcosnils WDYT?

Agree. Using underscores in method names is not usually a Java convention. @s-sathish would you mind refactoring the `_ro` to `Readonly`?. Let's use just one capital letter as it's a single word.

**Comment by s-sathish** [comment]
Hi @marcosnils @sazzad16 I've updated the code as per comments.

**Comment by marcosnils** [comment]
LGTM. I'll see why tests do not pass and approve.

**Comment by sazzad16** [comment]
@s-sathish As master branch was reset, could you please rebase your work?

**Comment by s-sathish** [comment]
Hi @sazzad16 I just did the rebase. Please check.

**Comment by marcosnils** [comment]
hey @s-sathish seems like you're rebasing with an old version of the master branch. Can you please check as tests dont pass?

**Comment by marcosnils** [comment]
Done!. Thx a lot @s-sathish for the patience and the effort.

**Pull request merged**
