### PR TITLE
implementing pexpire for ShardedJedis

### PR DESCRIPTION
**Pull request by nykolaslima**
This missing method was related by @Tavio.

Can you guys review please @HeartSaVioR @marcosnils?

### CODE REVIEW

**Comment by nykolaslima** [comment]
Hey guys, looks the build failed but I don't think that it's because of my change.

**Comment by HeartSaVioR** [comment]
@nykolaslima 
Sentinel failover test is having timing issue. It's fixed. 
Btw, we can add pexpire() to interface (BinaryJedisCommands, JedisCommands, BinaryRedisPipeline, RedisPipeline) and implement missed methods if it exists.
We always missed commands because some methods don't rely on interfaces.

**Comment by HeartSaVioR** [comment]
Oh, I missed to say thanks for your effort! :)

**Comment by nykolaslima** [comment]
@HeartSaVioR can you take a look please?

**Comment by HeartSaVioR** [comment]
Great! LGTM.

**Comment by HeartSaVioR** [comment]
Again, it adds missed spots so I labeled it with 2.6.3.
Seems like if we release minor version faster, I can label this to 2.7.0 too.

**Comment by nykolaslima** [comment]
@xetorthio @marcosnils Do you guys have any consideration on this? Can we merge it?

**Comment by xetorthio** [comment]
I think we can merge this! Thanks!

**Comment by xetorthio** [comment]
Shouldn't we have a test for this?

**Comment by HeartSaVioR** [comment]
We didn't test commands with Pipeline, ShardedJedis, JedisCluster. 
That's the point what I said.
Longer test duration with more tests duplication but more safeness, vs current.

**Comment by nykolaslima** [comment]
@xetorthio done! Any other considerations?

**Comment by marcosnils** [comment]
@nykolaslima, PR looks good

**Comment by marcosnils** [comment]
Downmerged to 2.6 and 2.7

**Pull request merged**
