### PR TITLE
Refactor imports

### PR DESCRIPTION
**Pull request by sazzad16**

### CODE REVIEW

**Comment by marcosnils** [comment]
LGTM!.

**Comment by marcosnils** [comment]
@sazzad16 is there a reason this can't go into 2.9.1?

**Comment by sazzad16** [comment]
@marcosnils I was concerned about how much I'll be able to backport to 2.9, let alone 2.10. However, I can give that a try.

Changing milestone.

**Comment by HeartSaVioR** [comment]
I guess it doesn't bring any bugfix and also any improvement, so I don't mind even if it will be merged in only 3.0.0. Backporting is already a huge pain: Let's avoid unnecessary hurdle.

**Comment by sazzad16** [comment]
Merged into master, 2.10, 2.9.

**Pull request merged**
