### PR TITLE
Disable protected mode for test environment

### PR DESCRIPTION
**Pull request by HeartSaVioR**
* this makes whole tests fail

This resolves the build failure what @gogeof reported.
https://github.com/xetorthio/jedis/issues/1370#issuecomment-246120348

@marcosnils @xetorthio Please review this, and confirm it doesn't fail on Linux.

### CODE REVIEW

**Comment by HeartSaVioR** [comment]
I don't know when/why it was changed... Only clear thing is that without patch at least OSX build is failing.

**Comment by marcosnils** [comment]
@heartsavior LGTM!. Thx for digging

**Comment by HeartSaVioR** [comment]
@marcosnils Not at all. I'd like to thank @gogeof to report this. I just follow his/her report.

**Comment by marcosnils** [comment]
I still believe it's weird that we needed this for OSX stuff to pass and in linux it worked without problem... But I don't mind that much because it's just for testing.

**Comment by HeartSaVioR** [comment]
Could you test with latest Redis unstable branch now without this patch? Actually I didn't see this before, and saw this after @gogeof reported.

**Comment by marcosnils** [comment]
@HeartSaVioR tests pass in linux without this patch, that's why I believe it's super strange that we need to enable this in OSX. This is a redis configuration which **should** be independent from the underlying OS :confused:

**Comment by HeartSaVioR** [comment]
@marcosnils Yes agreed. Might be better to have a look more and report to Redis.

**Comment by HeartSaVioR** [comment]
Anyway I merged this into master, 2.8, 2.9 branches. I'll try to dig more when I have time.

**Pull request merged**
