### PR TITLE
JedisCluster support choosing database.

### PR DESCRIPTION
**Pull request by jiafu1115**
[Motivation]

JedisCluster should support choosing database instead of default 0.

[Modifications]

(1) add private member: database in JedisClusterInfoCache;
(2) add new constructor with database for JedisCluster;

[Result]

JedisCluster support choosing database.

### CODE REVIEW

**Comment by jiafu1115** [comment]
close it due to the cluser mode isn't support select db. refer to ERR SELECT is not allowed in cluster mode

**Comment by yimiaoxiehou** [comment]
This submit code isn't access ? It already not support now?

**Comment by yimiaoxiehou** [comment]
@jiafu1115

**Comment by jiafu1115** [comment]
@yimiaoxiehou  not support it due to cluster mode not support it

**Pull request closed without merging**
