### PR TITLE
adding constructor that receives both name and weight

### LINKED ISSUE #825: JedisShardInfo cannot set both the name and weight
Hi, JedisShardInfo cannot set both the name and weight, because now I need to them.
Can add the following constructor method that includes name and weight parameters:

    public JedisShardInfo(String host, int port, String name, int weight, int timeout)

### PR DESCRIPTION
**Pull request by nykolaslima**
closes #825

### CODE REVIEW

**Comment by marcosnils** [comment]
:+1: looks good. Waiting for more reviews.

**Comment by HeartSaVioR** [comment]
Looks good to me, too.

**Comment by HeartSaVioR** [comment]
Thanks @nykolaslima , I merged this into master, 2.6, 2.7 branches.

**Comment by nykolaslima** [comment]
Thank you!

**Pull request merged**
