### PR TITLE
Fix for 'ERR max number of clients reached'  MasterListener Thread death

### PR DESCRIPTION
**Pull request by sheinbergon**
Hi @marcosnils @HeartSaVioR  @xetorthio 

I've created a test case for issue #1329  
Note that this PR doesn't yet include the actual fix ( Change the type of exception  catched to a broader one ) just the test that should fail in the current scenario. I'll add once we confirm the test is valid and up to standards

Haven't gotten round to running it yet though . Let me know what you think

### CODE REVIEW

**Comment by sheinbergon** [comment]
@marcosnils @HeartSaVioR  my tests are failing because config set/get is not supported for redis-sentinel :disappointed:  - http://stackoverflow.com/questions/30376639/redis-sentinel-how-to-get-config-value

I'd like to hear your ideas on how to tackle this (aside from writing command line execution integrations to change values in the config file and restart it). Tnx

**Comment by sheinbergon** [comment]
There is this PR https://github.com/antirez/redis/pull/2777 , but it looks like it never made it to production

**Comment by sheinbergon** [comment]
@marcosnils any response here ?

**Comment by HeartSaVioR** [comment]
@sheinbergon 
Sorry for the late update. Seems like most of changes are indentation mismatch. Could you follow our code style? hbase-formatter.xml is for that, and you can import this to your IDE.
You can even `make format` to reformat whole things but it also change javadoc format and other files so it's only for fixing whole messed things.

I'll take a look at again when formatting issue is gone.

**Comment by HeartSaVioR** [comment]
@sheinbergon 
And if you can't make test because of the lack of Redis, you are not forced to do. I'm OK to drop the test.

**Comment by sheinbergon** [comment]
@HeartSaVioR per your approval , I'll fix this PR to contain only the fix for this scenario

**Pull request closed without merging**
