### PR TITLE
add redis4.0 module Command and test

### PR DESCRIPTION
**Pull request by jingbanghu**
redis4.0 module Command,like 
Object obj = jedis.moduleExecute("testmodule.simple", "testkey", "arg1","arg2");
can be executed.

@marcosnils  ,i rearranged the code,but test need module,it may be not work,please guide me

### CODE REVIEW

**Comment by sazzad16** [comment]
@jingbanghu Module load/list/unload commands are already present. What is it you're trying to add here?

**Comment by jingbanghu** [comment]
@sazzad16 Module  not exist command like moduleExecute

**Comment by sazzad16** [comment]
@jingbanghu I think I've understood what you're trying to say. However, your implementation is not proper. Did you check test log?
```
Tests run: 1, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 0.009 sec <<< FAILURE! - in redis.clients.jedis.tests.commands.ModuleCommandsTest
exec(redis.clients.jedis.tests.commands.ModuleCommandsTest)  Time elapsed: 0.004 sec  <<< ERROR!
redis.clients.jedis.exceptions.JedisDataException: ERR unknown command 'testmodule.simple'
	at redis.clients.jedis.tests.commands.ModuleCommandsTest.exec(ModuleCommandsTest.java:10)
```

**Comment by sazzad16** [comment]
Closing as per discussion in #1713

**Pull request closed without merging**
