### PR TITLE
Configure connection timeout in JedisPool and JedisSentinelPool

### PR DESCRIPTION
**Pull request by maxd**
I have separated timeout (`timeout` variable) to connection timeout (`connectionTimeout` variable) and read timeout (`soTimeout` variable) because in some cases need to specify short connection timeout and long read timeout.

### CODE REVIEW

**Comment by maxd** [comment]
One build job has been failed but other three is passed. So, I don't think that this is related to my changes.

**Comment by HeartSaVioR** [comment]
LGTM.

**Comment by marcosnils** [comment]
@maxd thanks for the contribution. I'm wondering if we should also change `JedisCluster` and `Jedis` constructors to allow multiple timeouts as well. 

@HeartSaVioR what do you think?

**Comment by HeartSaVioR** [comment]
@marcosnils 
Jedis constructors already have conn timeout and sock timeout.
JedisCluster constructors don't have it. I'm sure that it's better to have it. :)

**Comment by marcosnils** [comment]
@HeartSaVioR I didn't notice about `Jedis`. I guess adding it to `JedisCluster` would be the best as you said.

**Comment by HeartSaVioR** [comment]
@marcosnils Adding connection timeout to JedisCluster requires this PR, and I can take care of it later.
Please review it first. :)

**Comment by marcosnils** [comment]
@HeartSaVioR  LGTM!

**Comment by HeartSaVioR** [comment]
Merged into master and 2.7 respectively.

**Pull request merged**
