### PR TITLE
Add "make format" to easily reformat source code

### PR DESCRIPTION
**Pull request by HeartSaVioR**
After merging this PR, we should run "make format" into master, 2.6, 2.7 branches to up to date.

### CODE REVIEW

**Comment by HeartSaVioR** [comment]
@marcosnils 
Seems like master branch is already broken.
Should we run ```make format``` into master, 2.6, 2.7 branches and push to apply?

**Comment by marcosnils** [comment]
@HeartSaVioR I'll merge this PR first and then apply formatting.

**Comment by HeartSaVioR** [comment]
@marcosnils OK, great! Thanks for follow up!

**Comment by walles** [comment]
Automated in #2495.

**Pull request merged**
