### PR TITLE
#1867 add waitReplica in JedisCluster

### PR DESCRIPTION
**Pull request by gkorland**

### CODE REVIEW

**Comment by gkorland** [comment]
@marcosnils can you please review?

**Comment by gkorland** [comment]
@marcosnils ok I'll remove the test

**Comment by gkorland** [comment]
@marcosnils any more changes?

**Comment by marcosnils** [comment]
I'll mark this as ready to merge as the change is prettry trivial.

**Comment by marcosnils** [comment]
@gkorland plz check @smadasu comments. I'll merge once those are fixed.

**Comment by sazzad16** [comment]
LGTM!

**Comment by gkorland** [comment]
@marcosnils can the PR be merged?

**Comment by sazzad16** [comment]
Merged into master, 2.10.

**Pull request merged**
