### PR TITLE
issue #2153 - honor sentinel configuration params within `MasterListener`

### LINKED ISSUE #2153: Jedis MasterListener Sentinel listeners NOAUTH error
JedisSentinelPool  successfully connects to sentinel servers and expect the listeners to attach to Sentinels. 

Once started the Listeners are failing 
356 [main] INFO redis.clients.jedis.JedisSentinelPool  - Redis master running at 10.90.69.81:6379, starting Sentinel listeners...
426 [MasterListener-xxx-master-[server:26379]] ERROR redis.clients.jedis.JedisSentinelPool  - Lost connection to Sentinel at server:26379. Sleeping 5000ms and retrying.

redis.clients.jedis.exceptions.JedisDataException: NOAUTH Authentication required.
	at redis.clients.jedis.Protocol.processError(Protocol.java:132)
	at redis.clients.jedis.Protocol.process(Protocol.java:166)
	at redis.clients.jedis.Protocol.read(Protocol.java:220)
	at redis.clients.jedis.Connection.readProtocolWithCheckingBroken(Connection.java:318)
	at redis.clients.jedis.Connection.getUnflushedObjectMultiBulkReply(Connection.java:280)
	at redis.clients.jedis.Connection.getObjectMultiBulkReply(Connection.java:285)
	at redis.clients.jedis.Jedis.sentinelGetMasterAddrByName(Jedis.java:3042)
	at redis.clients.jedis.JedisSe
 

Write here what happens instead ...
 Created a simple program to create JedisPool.

Create Log4j ConsoleAppender

_log4j.addAppender(new ConsoleAppender(new PatternLayout(PatternLayout.TTCC_CONVERSION_PATTERN)));
Call : new JedisSentinelPool(masterName, sentinels, poolConfig, timeout, timeout, accessKey, database,   
				clientName, timeout, timeout, sentinelAccessKey, sentinelClientName);

Generates 0 [main] INFO redis.clients.jedis.JedisSentinelPool  - Trying to find master from available Sentinels...
22 [main] DEBUG redis.clients.jedis.JedisSentinelPool  - Connecting to Sentinel server:26379
354 [main] DEBUG redis.clients.jedis.JedisSentinelPool  - Found Redis master at 10.90.69.81:6379
356 [main] INFO redis.clients.jedis.JedisSentinelPool  - Redis master running at 10.90.69.81:6379, starting Sentinel listeners...
426 [MasterListener-yte-master-[server]] ERROR redis.clients.jedis.JedisSentinelPool  - Lost connection to Sentinel at server:26379. Sleeping 5000ms and retrying.
redis.clients.jedis.exceptions.JedisDataException: NOAUTH Authentication required.
	at redis.clients.jedis.Protocol.processError(Protocol.java:132)
	at redis.clients.jedis.Protocol.process(Protocol.java:166)
	at redis.clients.jedis.Protocol.read(Protocol.java:220)
	at redis.clients.jedis.Connection.readProtocolWithCheckingBroken(Connection.java:318)
	at redis.clients.jedis.Connection.getUnflushedObjectMultiBulkReply(Connection.java:280)
	at redis.clients.jedis.Connection.getObjectMultiBulkReply(Connection.java:285)
	at redis.clients.jedis.Jedis.sentinelGetMasterAddrByName(Jedis.java:3042)
	at redis.clients.jedis.JedisSentinelPool$MasterListener.run(JedisSentinelPool.java:313)
435 [MasterListener-yte-master-[sever:26379]] ERROR redis.clients.jedis.JedisSentinelPool  - Lost connection to Sentinel at RT55B10097DV00:26379. Sleeping 5000ms and r

Jedis  3.20
java version "1.8.0_241"
Sentinel version 5.1

### PR DESCRIPTION
**Pull request by timmixell**
I could use some assistance/direction on proper unit test coverage, but I confirmed that the change addresses issue 2153 in our environment. Thank you!

Closes #2124 
Resolves #2153

### CODE REVIEW

**Comment by timmixell** [comment]
My sincere apologies. I didn't realize that there were already open PRs addressing this issue when I submitted this yesterday. Upon closer inspection, it looks like [this PR](https://github.com/xetorthio/jedis/pull/2124) would handle the scenario more gracefully when the target Sentinel is unavailable (i.e. if `j.auth()` throws a `JedisException`). I'm pretty sure this PR should be closed out in favor of #2124.

**Comment by sazzad16** [comment]
@timmixell Could you please move all the changes including new Jedis object creation after `if` block of *double check*?

**Comment by gkorland** [comment]
This file seems like it needs a full refactor

**Comment by gkorland** [comment]
And it seems like we're missing a test to test this use case,

**Comment by timmixell** [comment]
@gkorland , I'll get one in. I wasn't sure if this PR was going to survive, given that there are a couple other PRs addressing this issue.

**Comment by timmixell** [comment]
@gkorland I'm struggling a bit on the best approach to write a unit test to support this use case. Do you have any suggestions? Thanks!

**Comment by sazzad16** [comment]
@gkorland Perhaps we can merge it right now and create a new task to write test(s). WDYT?

**Pull request merged**
