### PR TITLE
Update Apache Commons Pool2 to 2.5.0

### PR DESCRIPTION
**Pull request by Lactem**

### CODE REVIEW

**Comment by marcosnils** [comment]
LGTM!.

**Comment by sazzad16** [comment]
@marcosnils We're for 2.6.1 in #1832 . Do we really need this before that?

**Comment by gkorland** [comment]
I moved it to 3.1.0 waiting for 2.6.1 to be released

**Comment by marcosnils** [comment]
Let's close this in favor of #1832

**Pull request closed without merging**
