### PR TITLE
Add missing methods in RedisPipeline and BinaryRedisPipeline

### LINKED ISSUE #1524: Missing method in RedisPipeline interface.
Missing method in RedisPipeline interface:

Response<Long> pttl(String key);
Response<String> set(String key, String value, String nxxx, String expx, int time);
Response<String> psetex(String key, long milliseconds, String value);

jedis ver: 2.9.0

### PR DESCRIPTION
**Pull request by sazzad16**
Based on #1531, thanks to @PhantomThief

Closes #1531 
Closes #1524

### CODE REVIEW

**Comment by sazzad16** [comment]
@HeartSaVioR @marcosnils ?

**Comment by jiafu1115** [comment]
LGTM @marcosnils

**Comment by gkorland** [comment]
@sazzad16 do you think it should be part of 3.0.1

**Comment by sazzad16** [comment]
@gkorland OK.

**Pull request merged**
