### PR TITLE
Add SSL support to JedisCluster

### LINKED ISSUE #1210: SSL/TLS Support for JedisCluster
I'm going to start working on SSL/TLS support for JedisCluster.

### PR DESCRIPTION
**Pull request by sazzad16**
This is a rebased version of #1550 #1849 
Original author: Jordan Rodak (@joroda)

Resolves #1210 
Closes #1849

### CODE REVIEW

**Comment by sazzad16** [comment]
@marcosnils @gkorland ping

**Comment by gkorland** [comment]
@sazzad16 should it merged to master or to 2.10.0 branch?

**Comment by sazzad16** [comment]
@gkorland I think so. WDYT?

**Comment by gkorland** [comment]
I think we shouldn't push anything else to 2.10.0 and just release it as is.
All the new things should be pushed to 3.0.0

**Comment by nchachkhiani** [comment]
Is this PR still going to be pushed to 3.0.0? I see 3.0.0 is already tagged for pre-release.

**Comment by analytically** [comment]
This didn't make it in 2.10 or 3.0.0.

**Comment by nchachkhiani** [comment]
Do we have an ETA for next release and if this PR is going to make it in?

**Comment by oscar-stripe** [comment]
Any update here? We are eagerly awaiting this.

**Comment by arkentos** [comment]
+1 Will like to know if we can push this out soon?

**Comment by bitsofinfo** [comment]
Will this ever be released?

**Comment by SimonOlenik** [comment]
We would need that asap.

**Comment by kriptor** [comment]
We would really need this released. Could we please get some ETA? Thx

**Comment by hradilf** [comment]
Hi,
please, is there any estimation and plan, if/when whit feature will be available in v2.10.x?

We are currently running on v2.9.0, using spring-data and we have to start to use SSL on Redis Enterprise.

Thanks for update.

**Comment by hradilf** [comment]
@sazzad16 Please, could you add estimation when it could be added into 2.10.x? The latest version is not compatible with spring-data-redis. Thank you.

**Comment by gkorland** [comment]
@hradilf notice spring-data-redis 2.2.0 is based on jedis 3.x

**Comment by hradilf** [comment]
@gkorland  2.2.0 is still only RC. 
Do  you know if this issue will be merged also into 2.10.x? 
Any estimation when will be official release 3.1.0? Thank you.

**Comment by gkorland** [comment]
@hradilf 3.1.0-rc was just released today, if there won't be no surprises we'll probably release 3.1.0 by the end of the week.

**Pull request merged**
