### PR TITLE
Add dump and restore into JedisCluster

### PR DESCRIPTION
**Pull request by sunsuk7tp**
Here let me add missing [DUMP](https://redis.io/commands/dump) and [RESTORE](https://redis.io/commands/restore) for `(Binary)JedisCluster` also.

### CODE REVIEW

**Comment by sunsuk7tp** [comment]
As well as existing `(Binary)Jedis`'s methods, I dare not to add methods in interfaces for now.
But I suppose they should be defined to `(Binary)JedisClusterCommands` interfaces.

**Comment by sazzad16** [comment]
@sunsuk7tp IMO, you should add methods in interfaces. Not only in cluster interfaces, but also in other interfaces, if you can.

**Comment by sazzad16** [comment]
@HeartSaVioR @marcosnils Would we still keep return of dump and argument of restore as `byte[]`?

**Comment by sunsuk7tp** [comment]
@sazzad16 Added into all interfaces.

**Comment by sazzad16** [comment]
LGTM! @HeartSaVioR @marcosnils

**Comment by marcosnils** [comment]
LGTM!

**Comment by sazzad16** [comment]
Merged into master, 2.10.

**Comment by sazzad16** [comment]
Merged into master, 2.10. Thanks @sunsuk7tp for contribution!

**Pull request merged**
