### PR TITLE
Type inference for generic instance creation

### PR DESCRIPTION
**Pull request by ullenius**
Type inference for generic instance creation. 
* Replacing redundant code `<T>` with` <>` for inferred type

This feature was added in Java 7 back in 2011 (!). The` pom.xml` explicitly specifies Java 7 so this does not break anything.

**Minor refactoring:**

* Removing unused method parameter for private helper method
`GenericObjectPoolConfig poolConfig` is passed to the method but never used

* Declaring modifiers in recommended order (`static final)` 6fada2e

References: [Oracle docs](https://docs.oracle.com/javase/8/docs/technotes/guides/language/type-inference-generic-instance-creation.html)

### CODE REVIEW

**Comment by sazzad16** [comment]
@ullenius Are these all? Did you look for more codes similar to the changes you have made?

**Comment by ullenius** [comment]
> @ullenius Are these all? Did you look for more codes similar to the changes you have made?

@sazzad16 I added 3 more commits fixing similar stuff. 

There are 2 more occurrences in [ClusterScriptingCommandsTest](https://github.com/ullenius/jedis/blob/298043451168e5f379f0e4b075fbdd96395e0396/src/test/java/redis/clients/jedis/tests/commands/ClusterScriptingCommandsTest.java#L147-L150) that I did not change. 

I'm somewhat reluctant to modify the tests given that they fail to to run as it is.

**Comment by sazzad16** [comment]
@ullenius Let us know when you're done changing.

**Comment by ullenius** [comment]
> @ullenius Let us know when you're done changing.

@sazzad16 I'm done, thanks.

**Pull request merged**
