### PR TITLE
Impl zpopmin zpopmax

### PR DESCRIPTION
**Pull request by kommradHomer**
I have implemented 2 commands for the Sorted Sets . ZPOPMIN and ZPOPMAX

### CODE REVIEW

**Comment by marcosnils** [comment]
Can you please add this commands in `Pipeline` and `Cluster`? Here's an example of another PR which added those implementations as well. 

https://github.com/xetorthio/jedis/pull/1841/files

**Comment by kommradHomer** [comment]
Hello , I have added what i thought is missing and committed , after your warning. Do i need to open another pull request ? This is the first time i'm using this mechanism . Thank you

**Comment by sazzad16** [comment]
@marcosnils We already have a pending PR for zpopmax at #1968

**Comment by kommradHomer** [comment]
@sazzad16  how about zpopmin ? should i cancel or close this PR ?

**Comment by marcosnils** [comment]
@kommradHomer yup, zpopmin is still needed. You can go ahead and send just that one. 

Apologies for the confusin.

**Comment by sazzad16** [comment]
@kommradHomer Thanks :)

**Pull request closed without merging**
