### PR TITLE
keep same code style

### PR DESCRIPTION
**Pull request by jiafu1115**
keep same code style between password setting with database selecting/clientName setting.

### CODE REVIEW

**Comment by marcosnils** [comment]
LGTM

**Comment by jiafu1115** [comment]
@marcosnils OK, Thanks, Let's wait @HeartSaVioR or others' update!

**Comment by HeartSaVioR** [comment]
LGTM too.

**Comment by marcosnils** [comment]
Merged to master and 2.10 / 2.9 respectively.

**Pull request merged**
