### PR TITLE
Documentation:

### PR DESCRIPTION
**Pull request by OgmaJ**
Adding JavaDoc for the basic commands of interface BasicCommands.
Very usefull in some work environment, where internet connection is unavailable.

### CODE REVIEW

**Comment by marcosnils** [comment]
@OgmaJ would you mind rebasing plz. I promise I'll merge this time.

**Comment by OgmaJ** [comment]
Hi Marcos,

I'm in holiday and came back at the end of the week.
I will redo the modification on the latest build.

Feel free to contact me in case of any issue/suggestion.

Regards

Julien Demontis

2015-08-16 23:12 GMT+02:00 Marcos Nils <notifications@github.com>:

**Comment by marcosnils** [comment]
@OgmaJ ping?

**Comment by OgmaJ** [comment]
Hi Marcos,

I totally forgot you.

You will find the merge request at the pull : 1181


   -  https://github.com/xetorthio/jedis/pull/1181


Regards

Julien

2015-12-04 19:46 GMT+01:00 Marcos Nils <notifications@github.com>:

**Comment by marcosnils** [comment]
closed by #1181

**Pull request closed without merging**
