### PR TITLE
Implement fix in JedisPubSub to support PING/PONG during subscription.

### PR DESCRIPTION
**Pull request by Anisotrop**
Had to change pom.xml in order to pass the javadoc generation.

[...]
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 01:35 min
[INFO] Finished at: 2016-05-12T16:39:27+03:00
[INFO] Final Memory: 24M/60M
[INFO] ------------------------------------------------------------------------
make stop
[...]

### CODE REVIEW

**Comment by marcosnils** [comment]
LGTM. Once another reviewer approves we can merge.

**Comment by HeartSaVioR** [comment]
LGTM, too. Thanks for the contribution.
Btw, I think it would be better when JedisPubSub automatically does PING-PONG internally, but it should be done with separate issue.

**Comment by HeartSaVioR** [comment]
Merged to master, 2.8, 2.9 branches respectively!

**Comment by Anisotrop** [comment]
@marcosnils, @HeartSaVioR Hi guys, thanks for reviewing and merging ! Do you have any plans to release any time soon ?

**Comment by xbwen** [comment]
It would be perfect if BinaryJedisPubSub also have this feature.

**Pull request merged**
