### PR TITLE
Expose pool borrow stats.

### PR DESCRIPTION
**Pull request by jayanderson**
I'd like to get at these borrow statics to help inform how we should setup our connection pool.

### CODE REVIEW

**Comment by marcosnils** [comment]
@jayanderson seems reasonable. I don't believe that tests are needed as it's pretty much straightforward and Mex/Mean pool borrow doesn't seem easy to est. 

@HeartSaVioR what do you think?

**Comment by HeartSaVioR** [comment]
@jayanderson @marcosnils 
Looks great. Since it just uses Commons Pool 2 feature, I think we don't need to make test.

**Comment by HeartSaVioR** [comment]
Merged into master, 2.7, 2.8 branches respectively.
@jayanderson Thanks for contribution!

**Comment by jayanderson** [comment]
@HeartSaVioR, @marcosnils Great thanks!

**Pull request merged**
