### PR TITLE
Attempted fix for #1229 - multiple entries in node list for same host

### PR DESCRIPTION
**Pull request by roblg**
Hey all, this is my attempt at a fix for #1229. It sounded like the approach seemed reasonable, so I thought I'd take a stab at it.

Tests pass for me locally against the unstable branch of redis. I tried to add a new test for my specific case where equality check in HostAndPort fails, so multiple nodes end up in the list, but there's already code to convert `127.0.0.1` --> `localhost` in `HostAndPort`, so it wasn't clear how I'd be able to test my particular situation safely in many different test environments.

I based my fix on the 2.8 branch, but I can switch it to the 2.9 or master branches if that makes more sense.

Thanks for considering!

### CODE REVIEW

**Comment by marcosnils** [comment]
@roblg thanks for submitting a patch. I believe it's heading in the proper direction. In order to test this you might try to setup JedisCluster like this:

```java
    Set<HostAndPort> jedisClusterNode = new HashSet<HostAndPort>();
    jedisClusterNode.add(new HostAndPort("localhost", 7379));
    jedisClusterNode.add(new HostAndPort("some_other_host", 7379));
    JedisCluster jc = new JedisCluster(jedisClusterNode);
    // Assert on jc.getClusterNodes().size()
```
With the previous code JedisCluster will populate all the hosts in the cluster plus "some_other_host" (even though it's invalid). Your test needs to assert that supplied hosts are not added into the node list.

**Comment by roblg** [comment]
@marcosnils good call. I realized while I was writing the "invalid host" test that I was mistaken about how the 127 vs. localhost equality was happening. I actually got the "broken" behavior if I created a `new HostAndPort("localhost", 7379)`, so I included a test for that as well.

PR updated.

**Comment by marcosnils** [comment]
@roblg LGTM. I'd like @HeartSaVioR or @xetorthio to review before merging. 

I'd also like to schedule this for 2.9 as it changes the way JedisCluster is initializing. Even though I believe it "shouldn't" cause any problems, I propose to move it to a minor release just in case

**Comment by HeartSaVioR** [comment]
@roblg 
LGTM. Thanks for the work!
Btw, it would be more sense to move to master branch. We can take care of backporting if necessary.

**Comment by roblg** [comment]
@HeartSaVioR @marcosnils would you like me to update the PR to be based on master?

**Comment by marcosnils** [comment]
@roblg yes please. We'll take care to downmerge to 2.9

**Comment by HeartSaVioR** [comment]
Yes, if you don't mind. Thanks in advance!

**Comment by HeartSaVioR** [comment]
@marcosnils You're really fast! lol

**Comment by marcosnils** [comment]
@HeartSaVioR :tongue: going to bed. Can you please merge once changes are made?. Thx!.

**Comment by HeartSaVioR** [comment]
@roblg Ah, one thing we didn't say... PR should be re-created against master. It's a limitation of Github PR.

**Comment by roblg** [comment]
@HeartSaVioR yeah that kind of surprised me. I've been using Bitbucket at work for several years. Got it sorted out though (I hope).

**Pull request closed without merging**
