### PR TITLE
Added 'pttl' command in remaining interfaces

### PR DESCRIPTION
**Pull request by sazzad16**

### CODE REVIEW

**Comment by marcosnils** [comment]
LGTM @HeartSaVioR ? I don't think this breaks backwards compatibility, so I'll mark it for 2.9

**Comment by sazzad16** [comment]
@marcosnils Could you please review [this](https://github.com/xetorthio/jedis/pull/1575) similar PR?
Sorry if this is not the right place to ask for.

**Comment by HeartSaVioR** [comment]
LGTM!

**Comment by HeartSaVioR** [comment]
@sazzad16 Sorry now this has conflicts between master. Could you rebase your change with latest? Thanks in advance!

**Comment by sazzad16** [comment]
@HeartSaVioR Please check now.

**Comment by sazzad16** [comment]
@HeartSaVioR @marcosnils Rebased!

**Comment by sunsuk7tp** [comment]
Why can't you support pttl for `BinaryJedisCluster` also though `BinaryJedis` has pttl?

**Comment by sazzad16** [comment]
@sunsuk7tp Thank you for noticing! As this PR is already tagged `READY TO MERGE`, I am not changing it. Added another PR #1653

**Comment by sazzad16** [comment]
Merged into master, 2.10, 2.9.

**Pull request merged**
