### PR TITLE
Use int instead of short

### PR DESCRIPTION
**Pull request by sazzad16**

### CODE REVIEW

**Comment by marcosnils** [comment]
@sazzad16 why `int` if short is big enough for the amount of possible slots?

**Comment by sazzad16** [comment]
@marcosnils How about [Why does the Java API use int instead of short or byte?](https://stackoverflow.com/questions/27122610/why-does-the-java-api-use-int-instead-of-short-or-byte)

**Comment by HeartSaVioR** [comment]
I'll wait for @marcosnils to approve as well, given that he participated to review.

**Comment by marcosnils** [comment]
LGTM

**Comment by sazzad16** [comment]
Merged into master, 2.10.

**Pull request merged**
