### PR TITLE
Added support for binary script eval/evalsha

### PR DESCRIPTION
**Pull request by janssk1**
You still need to add tests. Did not get the testsuite working

### CODE REVIEW

**Comment by marcosnils** [comment]
@janssk1 I see that you didn't make PipelineBase implement BinaryScriptingCommands. Is there a reason for that?

**Comment by marcosnils** [comment]
@janssk1 can you please craft the PR against the master branch so we can have the latest Jedis version working?. We'll take care to down merge it to the older versions.

Thx!.

**Comment by janssk1** [comment]
On master, MultiKeyPipelineBase already supports binary script invocations.

**Comment by marcosnils** [comment]
@janssk1 you're right. The proper way to proceed is to downmerge 3a1b3a21631a38241d56e00a22526285c8becfc7 to 2.7 and 2.8 respectively. I'll try to get it done by today, keep watching the thread.

**Pull request closed without merging**
