### PR TITLE
squid:S1118 - Utility classes should not have public constructors

### PR DESCRIPTION
**Pull request by m-ezzat**
This pull request is focused on resolving occurrences of Sonar rule squid:S1118 - Utility classes should not have public constructors

You can find more information about the issue here:

https://dev.eclipse.org/sonar/coding_rules#q=squid:S1118

Please let me know if you have any questions.

M-Ezzat

### CODE REVIEW

**Comment by marcosnils** [comment]
LGTM, waiting for more reviews

**Comment by marcosnils** [comment]
@m-ezzat please rebase with master so tests can run.

**Comment by HeartSaVioR** [comment]
LGTM

**Comment by HeartSaVioR** [comment]
Merged into master, 2.8, 2.9 respectively.

**Pull request merged**
