### PR TITLE
Added final to the parameters of public methods

### PR DESCRIPTION
**Pull request by sazzad16**

### CODE REVIEW

**Comment by marcosnils** [comment]
LGTM!

**Comment by HeartSaVioR** [comment]
LGTM. Thanks for contribution.

**Comment by marcosnils** [comment]
@sazzad16 this needs to be downmerged to 2.9 and 2.10. I'll let you go through it as it's an easy change. Let me know if you need some help.

**Comment by sazzad16** [comment]
@marcosnils I'd appreciate any help. Thanks!

The main problem I'm facing in downmerging this, is mostly because one or more `Override` commits weren't downmerged.

**Comment by sazzad16** [comment]
@marcosnils @HeartSaVioR Downmerging done!

Working on #1077 has paid off.

**Pull request merged**
