### PR TITLE
Fixes #864

### LINKED ISSUE #864: Class BinaryShardedJedis does not have method "public String set(final byte[] key, final byte[] value, final byte[] nxxx, final byte[] expx, final long time)"
As you see, could not find the method, is there a reason for this?

### PR DESCRIPTION
**Pull request by auhig**
Fixes #864
 Add method "public String set(byte[] key, byte[] value, byte[] nxxx, byte[] expx, long time)"

### CODE REVIEW

**Comment by marcosnils** [comment]
@auhig LGTM. Once another review checks it we'll merge.

**Comment by nykolaslima** [comment]
It would be nice to add one test to `AllKindOfValuesCommandsTest`. What do you guys think @marcosnils @auhig?

**Comment by HeartSaVioR** [comment]
LGTM, too. But I also think it would be better to have unit test.
@auhig Could you apply it? Thanks in advance!

**Comment by auhig** [comment]
Unit testing is good, but I could not find some classes for testing commands of BinaryShardedJedis, since these classes use the Jedis instance. Is it necessary to create a new UT class?

**Comment by nykolaslima** [comment]
@auhig you should create the test in this class: `AllKindOfValuesCommandsTest `.

This class already has a `jedis` instance inherited from `JedisCommandTestBase`;

**Comment by nykolaslima** [comment]
LGTM!

**Comment by marcosnils** [comment]
:+1:

**Comment by HeartSaVioR** [comment]
LGTM, too.

**Comment by marcosnils** [comment]
I'll merge.

**Comment by marcosnils** [comment]
Merged to master and 2.7

**Pull request merged**
