### PR TITLE
code clean up: remove unused imports

### PR DESCRIPTION
**Pull request by jiafu1115**
code clean up

### CODE REVIEW

**Comment by marcosnils** [comment]
@jiafu1115 thx for the path. Do you know if these are **all** unsued Jedis imports or some that you just found?. 

I just wanted to take the opportunity that we're fixing this across the whole project.

**Comment by jiafu1115** [comment]
@marcosnils yes. They are all. I found one then I fix all.^v^

**Comment by marcosnils** [comment]
Perfect, I'll merge as it's a quick change. Thx!

**Comment by jiafu1115** [comment]
Thanks! we will make jedis more clearer!

**Comment by marcosnils** [comment]
Downmerged!.

**Pull request merged**
