### PR TITLE
Add support to set password in JedisCluster

### PR DESCRIPTION
**Pull request by marcosnils**
Even though the Redis Cluster spec doesn't say anything about it and the redis community still hasn't agreed about how to handle it, seems like many Redis / Jedis users need this functionality. 

I've implemented a very basic (I didn't add the parameter in all the possible constructor combinations) approach by just forwarding the password parameter to the inner JedisPool and discovery instances.

### CODE REVIEW

**Comment by marcosnils** [comment]
@HeartSaVioR plz review.

**Comment by charpty** [comment]
@HeartSaVioR Please review and merge this, we really need this feature.
Accuratlly, many coders need this feature.
Thanks!!!

**Comment by marcosnils** [comment]
@charpty if you need this urgenly you can always merge the PR and provide feedback

**Comment by marcosnils** [comment]
@charpty if you need this urgenly you can always merge the PR and provide feedback

**Comment by HeartSaVioR** [comment]
Sorry it's been a long time far from this issue. LGTM.
@marcosnils Thanks for the great work!

**Comment by HeartSaVioR** [comment]
Resetting the milestone to 2.9.0 since it's not a bug, but just a new feature which is support for Azure environment.

@marcosnils Please reset milestone to 2.8.2 and backport if you think we need to ship this to bugfix release. Thanks!

**Comment by HeartSaVioR** [comment]
I merged master and 2.9 branch. Thanks!

**Comment by marcosnils** [comment]
@HeartSaVioR It's ok, we can include it in 2.9.

**Comment by alexs20** [comment]
When do you plan to release 2.9?
We need the cluster password functionality... thanks.

**Comment by PunKeel** [comment]
+1 alexs20

**Comment by marcosnils** [comment]
@alexs20 @PunKeel we have some PR's and issues we need to work on before releasing 2.9. Unfortunately we can't commit to a date for the moment, but if you need this urgently you can always build Jedis from source.

**Comment by PunKeel** [comment]
@marcosnils Thanks & no issue on this side for me, just didn't want to use an unstable API ;-)

**Comment by marcosnils** [comment]
@PunKeel all jedis official branches (master / 2.9 and 2.8) are fully tested and stable. We usually hold releases for sometime because we try to include all opened issues.

**Comment by alexs20** [comment]
@marcosnils Sure we can. And I personally done. And it works perfect. But unfortunately our company policy against using SNAPSHOT jars in production environment. Fortunately we have a couple month before release, but if the delay will be too long then we have no choice but to search for alternative solutions. I just need a raw ETA like month, two, three, just to report something to my boss.

**Comment by qqj1979** [comment]
waiting for jedis official branches  2.9 .

**Comment by liuwenru** [comment]
how can i connect redis cluster with password, can give some example or write to the wiki

**Comment by alexs20** [comment]
@liuwenru, use this constructor:
JedisCluster(HostAndPort node, int connectionTimeout, int soTimeout,
                      int maxAttempts, String password, final GenericObjectPoolConfig poolConfig) 

soTimeout is socket read timeout

**Pull request merged**
