### PR TITLE
changing DB datatype from Long to int to save some bytes

### PR DESCRIPTION
**Pull request by nykolaslima**
@HeartSaVioR as discussed in the other PR #835, changing DB datatype from `Long` to `int`.

### CODE REVIEW

**Comment by marcosnils** [comment]
Already discussed in #835. Labeling to be included in 3.0 release.

**Comment by HeartSaVioR** [comment]
Since we've discussed and agreed to apply it from next major release, I'll merge this in.

**Comment by HeartSaVioR** [comment]
Thanks @nykolaslima , I merged it into master branch, which matches next major release.

**Comment by HeartSaVioR** [comment]
After merging, build is failing. I'll fix it right now.

**Comment by HeartSaVioR** [comment]
I fixed a bug introduced from merging several PRs by ac26f913626b782ca2c41fd87a46e3f1ebf096b3.
Maybe we have to avoid automatic merge and run unit tests before merging as possible.

**Comment by nykolaslima** [comment]
Thank you!

**Pull request merged**
