### PR TITLE
Reduce code redundancy

### PR DESCRIPTION
**Pull request by sazzad16**
- Reduce redundancy in codes which are mostly related to SSL/TLS support.
- Add constructors in `JedisPool`

### CODE REVIEW

**Comment by sazzad16** [comment]
@HeartSaVioR @marcosnils

**Comment by marcosnils** [comment]
Nice refactor LGTM!

**Comment by sazzad16** [comment]
@marcosnils Just added a small change. Please check again.

**Comment by sazzad16** [comment]
Merged into master.

**Comment by sazzad16** [comment]
Backported to 2.10 with deprecation.

**Pull request merged**
