### PR TITLE
add function of Redis Bloom Filter for Jedis and Jedis Cluster

### PR DESCRIPTION
**Pull request by joyang1**
add function of Redis Bloom Filter for Jedis and Jedis Cluster

### CODE REVIEW

**Comment by marcosnils** [comment]
Is this part of a Redis module?. We don't usually add first class functions for Redis modules to the API. 
You can extend Jedis and wrap it around a custom library for that. 

@smadasu @gkorland thoughts?

**Comment by joyang1** [comment]
I think redis bloom filter is use usually now.  So I hope you can add this functions. 
But if you think this is not necessary, I can only wrap Jedis around a custom library.
thanks~~~
@marcosnils

**Comment by gkorland** [comment]
@joyang1 please check https://github.com/RedisLabs/JReBloom/

**Comment by joyang1** [comment]
@gkorland , I know this, this I can customize, but I want to use JedisCluster for Rebloom.
So I need use Jedis.
I think this is necessary to integrated with Jedis. 
But if you think this is not necessary, I can only wrap Jedis around a custom library.
thanks~~~

**Comment by joyang1** [comment]
@gkorland  I know, but JedisCluster is not customize, JedisCluster use Jedis class to read Redis server. 
I hope you can let us to customize JedisCluster.
Thanks~~~

**Comment by joyang1** [comment]
@gkorland  I want to do this PR in JReBloom. 
But you need to let me Customize JedisCluster.
It's OK?

**Comment by marcosnils** [comment]
What about extending JedisCluster in JReBloom and add the methods here?

**Pull request closed without merging**
