### PR TITLE
squid:UselessParenthesesCheck - Useless parentheses around expression…

### PR DESCRIPTION
**Pull request by m-ezzat**
This pull request is focused on resolving occurrences of Sonar rule squid:UselessParenthesesCheck - Useless parentheses around expressions should be removed to prevent any misunderstanding

You can find more information about the issue here: https://dev.eclipse.org/sonar/coding_rules#q=squid:UselessParenthesesCheck

Please let me know if you have any questions.

M-Ezzat

### CODE REVIEW

**Comment by marcosnils** [comment]
Even though it LGTM I believe the pointed cases are not misunderstanding at all.

**Comment by HeartSaVioR** [comment]
LGTM, but I don't see the benefit at all. 
We don't need to apply all suggestions, so I'd like to ignore trivial things and see with minor or higher.

**Comment by HeartSaVioR** [comment]
@marcosnils If you can see the benefit feel free to merge, but if not, let's just close this.

**Comment by marcosnils** [comment]
@HeartSaVioR agree, it's not supper important. It's just code readability.

**Pull request closed without merging**
