### PR TITLE
add JedisCluster password parameter

### PR DESCRIPTION
**Pull request by zhouhuabin**
when redis cluster running requirepass mode,create JedisCluster instance must provide password,so i suggest add password parameter in constructor method like this:
 public JedisCluster(Set<HostAndPort> jedisClusterNode, int timeout, int maxRedirections,
      final GenericObjectPoolConfig poolConfig,String password) {
    super(jedisClusterNode, timeout, maxRedirections, poolConfig,password);
  }
relative other class is BinaryJedisCluster,JedisClusterConnectionHandler,JedisClusterInfoCache,JedisSlotBasedConnectionHandler

### CODE REVIEW

**Comment by zhouhuabin** [comment]
sorry ,i'm not skilled using Git in eclipse ,in fact just "add JedisCluster password parameter if cluster running with requirepass …"commit is what I want to pull

**Comment by marcosnils** [comment]
@zhouhuabin two comments:

Even though the `auth` command is implemented in RedisCluster, it's stil not clear what the redis creator want to do about it. Please see this thread for further info: https://groups.google.com/forum/#!searchin/redis-db/password/redis-db/Z8lMxTfDct8/fQY8slgbkYYJ. That's the main reason why we haven't implemented it in Jedis because it's most likely to be either decommissioned or changed .

Secondly, I'm aware that you just want us to merge one commit but it'd be easy for us if you fix the PR and leave just one commit.  Here's how you can do it: 

```
- Place in your code fork
- Do git checkout -b jedis_cluster_password 7dbf621820e9bc7474194e7d1428f4bc14c75570 // This will create a new branch from the lastest Jedis commit
- Do git cherry-pick 6c0f6e1f2d89b883c5f968c5892e2821840b1d04 //This will apply only the commit you wanted
- Do git push origin jedis_cluster_password //This will pull your branch to your jedis repo
- Open the PR from your jedis_cluster_password to jedis master branch
```

Please let us know if you have some more questions.

**Comment by zhouhuabin** [comment]
first thanks very much show me how to use git. i had make a branch jedis_cluster_password in my repo, thanks!

**Comment by marcosnils** [comment]
@zhouhuabin you can close this PR and open a new one with just the change in your branch

**Comment by lhcg** [comment]
@zhouhuabin which brache you develop on ? 2.7 or other?

**Comment by zhouhuabin** [comment]
i develop it on 3.0.0 master

**Pull request closed without merging**
