### PR TITLE
Implemented UNLINK command

### PR DESCRIPTION
**Pull request by sazzad16**

### CODE REVIEW

**Comment by marcosnils** [comment]
LGTM!. @HeartSaVioR ? @sazzad16 thx for your amazing contributions!.

**Comment by ilyabiryukov-r7** [comment]
@sazzad16 @marcosnils any update on this?

**Comment by HeartSaVioR** [comment]
LGTM.

**Comment by sazzad16** [comment]
Merged into master, 2.10.

**Pull request merged**
