### PR TITLE
Backport cluster-revised branch with backward compatible way

### LINKED ISSUE #987: Bring cluster-revised branch to 2.8
As Jedis 3.0 still has some features which we haven't decide how they're going to be implemented (I.E async) we need to downmerge #671 as it contains many features and improvements that users need as today

### PR DESCRIPTION
**Pull request by HeartSaVioR**
Closes #987

### CODE REVIEW

**Comment by christophstrobl** [comment]
Thank you @HeartSaVioR!
Just plugged your branch into Spring Data Redis and the branch for cluster support there. Tests passed. Well done!

**Comment by marcosnils** [comment]
Let's merge this :smile:

**Comment by HeartSaVioR** [comment]
@marcosnils :+1: Thanks!

**Comment by christophstrobl** [comment]
thanks!

**Comment by gregturn** [comment]
:+1:

**Pull request merged**
