### PR TITLE
Pull request to change visibility of getConnectionFromSlot method

### PR DESCRIPTION
**Pull request by saurabhygk**
For issue number: https://github.com/xetorthio/jedis/issues/1527

### CODE REVIEW

**Comment by marcosnils** [comment]
LGTM!. @HeartSaVioR @allanwax @xetorthio ?

**Comment by allanwax** [comment]
ok

**Comment by saurabhygk** [comment]
@HeartSaVioR @xetorthio I am sorry for trouble. Please review changes and help me out.

Thank you @marcosnils and @allanwax

**Comment by allanwax** [comment]
@HeartSaVioR @xetorthio @saurabhygk Since I'm not a git person (I'm still using svn very productively) I'm not used to using git tools to do various things.  I did check out the master to see what the current definition of the method is.  While there is potential for bad things to happen since you can now get directly at the connection, the ability to get the connection allows things like pipelining to happen, with the caveats that anything can happen between getting the connection and actually executing the action(s).  So I think the benefits outweigh the risks.  If issue come up in the future you can still do it the hard way if you really want to.

**Comment by saurabhygk** [comment]
@allanwx Thank you for your comment. I am sorry but can you please suggest me what kind of risk will be there with this method. By using this method we are taking the connection and perform the action with that connection only and its user/developer responsibility how to be behave with connection. Also one more thing in single redis connection Jedis supports pipeline then what's the issue with redis cluster. I am curious to know that why Jedis does not support pipeline on cluster.

**Comment by saurabhygk** [comment]
@allanwax sorry for typo in name

**Comment by allanwax** [comment]
@saurabhygk The risks are (a) the connection for the slot becomes invalid between the time you fetch it and use it (failover, network problems, etc.), (b) bad code: somebody gets the connection and does something with it that they shouldn't.  (a) can happen at any time so you need to code defensively. (b) is less likely but if someone writes bad code it can take down the whole program with errors and be hard to find.

But as I said, I think the benefits outweigh the risks.

**Comment by HeartSaVioR** [comment]
@saurabhygk 
I intentionally didn't implement JedisCluster with Pipeline because it is really hard to guarantee safeness. Please refer below discussion from Redis group: 
https://groups.google.com/d/msg/redis-db/4I0ELYnf3bk/Lrctk0ULm6AJ

**Comment by HeartSaVioR** [comment]
Sorry maybe commenting to #1527 would be right. Anyway the code change looks fine.

**Comment by allanwax** [comment]
@saurabhygk @HeartSaVioR I absolutely agree that trying things like pipeline on a cluster is inherently unsafe because of all the previously mentioned reasons.  If, however, you are tolerant of failure and bad data there may be some benefit.

I've written and published to the group several times my class called ReadOnlySlave which uses some of the ideas of bypassing the normal cluster logic and treating the slaves as individual servers.  It works and allows some parallel read operations (but not pipelined) on the cluster. **But** it also is monitoring slot movement and server failovers and tries to recover from them, with the ultimate fallback to do a regular read to the cluster.  The data I'm using does not have to be perfect and in my case will self-heal over time.

In other circumstances there is no tolerance for bad data and pipelining on the cluster will always fail eventually no matter how clever your program is.

So, getting the connection from the slot -- go ahead, but know that you can (and will) shoot yourself in the foot if you don't play by the rules.

**Comment by HeartSaVioR** [comment]
@saurabhygk Merged into master and 2.10 branches respectively.

**Comment by marcosnils** [comment]
Thx heart for taking care

**Comment by saurabhygk** [comment]
@HeartSaVioR Thank you very much for handling Pull Request. I will be continue my self to contribute in Jedis.

**Pull request merged**
