### PR TITLE
Handle local host reference automatically.

### PR DESCRIPTION
**Pull request by allanwax**
Handle IPV6 local host references.

### CODE REVIEW

**Comment by marcosnils** [comment]
@allanwax seems like some tests failed because of your change. To check them locally you can run `make test` from your Jedis root directory. 

Take into account that you need the to have the latest redis (unstable branch) installed.

**Comment by allanwax** [comment]
Hopefully these test failures do not impact others.

Testing is difficult on a pc.  I'll try your suggestions.

**Comment by marcosnils** [comment]
@allanwax don't worry. Test failres don't impact on others pull requests. If you need some help with tests just send me a hangout message to my email and I can give you a hand.

**Comment by allanwax** [comment]
@marcosnils  Apparently Windows was never designed to deal with Redis and Jedis.  I can't make the test as the developer libraries are not available for Windows using Cygwin.  Microsofts libraries for their own Redis port won't work.

I have updated the tests to be consistent with usage of local host.  The tests now pre-convert 127.0.0.1 to the local machine address so we are, so to speak, comparing apples with apples.  I have pushed it to my branch.  If you think this is sufficient, I will issue a pull request.

**Comment by marcosnils** [comment]
@allanwax there's no need to make another pull request as the PR automatically updates when you push new things to your branch (it's synchronized). 

However, I still see that tests are failing. I'll check your code in my computer and we'll continue our conversation here until we get it running :).

**Comment by HeartSaVioR** [comment]
@allanwax Some files are changed its mode. Could you please check? Thanks!

**Comment by allanwax** [comment]
@HeartSaVioR What do you mean by mode?

**Comment by HeartSaVioR** [comment]
@allanwax Its mode are changed from 644 to 755. You can see "Files changes" tab to see the following.

**Comment by allanwax** [comment]
I'll change to 644 and recommit/push

**Comment by allanwax** [comment]
Changing to 644 screwed up everything here.  I wiped and and reloaded.  I don't know why it is changing.

**Comment by allanwax** [comment]
I only see two errors in the Travis log and those involve that the expected exception is not the one that happens.  I wonder if the test needs to be changed.  Opinions wanted.

**Comment by marcosnils** [comment]
@allanwax I'll take a look in 10 mins

**Comment by allanwax** [comment]
@marcosnils [Still newbie] What needs to be done at this point.  My local branch indicates I'm up to date but the message above indicates I need to resolve some conflicts.  Do I need to do a `pull` request?

**Comment by sazzad16** [comment]
Closing in favour of #1468

**Pull request closed without merging**
