### PR TITLE
Introduce toString for Slowlog

### PR DESCRIPTION
**Pull request by Raul-**
This is to resolve issue 334. https://github.com/xetorthio/jedis/issues/334

### CODE REVIEW

**Comment by HeartSaVioR** [comment]
@Raul- 
Do you have some outputs which print slowlog after applying your PR? I'd like to see actual output. 
Making unit test is more appreciated way, but I wonder it is easy to reproduce slowlog.

Thanks in advance!

**Comment by Raul-** [comment]
Printing slowlog after the PR change: 107,1435827586,3,[SET, foo2, bar2] which is basically "id,timeStamp,executionTime,args".

I am not sure what kind of test would add value since it is a straightforward change. Do you have something particular in mind?

**Comment by HeartSaVioR** [comment]
Not at all. It seems to be enough.
LGTM.
Please wait for other collaborators to review. Thanks in advance!

**Comment by marcosnils** [comment]
LGTM too I re ran the tests so once they pass we can merge

**Comment by HeartSaVioR** [comment]
Thanks @Raul- I merged it to master and 2.8 branches.

**Comment by Raul-** [comment]
Thank you!

**Pull request merged**
