### PR TITLE
Adds MEMORY DOCTOR command

### PR DESCRIPTION
**Pull request by aeter**
Description:
* MEMORY DOCTOR command, https://redis.io/commands/memory-doctor

Testing:
* Ran ```TEST=ClientCommandsTest make test```, observed 0 test failures.

### CODE REVIEW

**Comment by marcosnils** [comment]
LGTM!.

**Comment by sazzad16** [comment]
@marcosnils Won't it be better to have a binary version for this command?

**Comment by aeter** [comment]
hi, I've separated a `memoryDoctor()` and a `memoryDoctorBinary()` implementation, as suggested. Let me know if the updated code makes sense to you. Cheers!

**Comment by sazzad16** [comment]
@aeter To clarify, I was trying to discuss with @marcosnils on alternate options. I didn't suggest anything to you.

**Comment by aeter** [comment]
Ok. Currently the code is similar to some other commands - `clientGetName/clientGetNameBinary`, `clientList/clientListBinary`, `slowlogGet/slowlogGetBinary`. If you guys have specific notes to the code, I'll try to address them. Thank you for the fast feedback on this PR.

**Comment by aeter** [comment]
Thank you for the review, @sazzad16! I've moved the tests under `ControlCommandsTest` - and retested locally with `TEST=ControlCommandsTest make test`.

**Comment by sazzad16** [comment]
@aeter Would you be able to add all MEMORY commands?

**Comment by aeter** [comment]
@sazzad16 - thanks for the discussion. I was also thinking about the other MEMORY commands. To be honest, I doubt I can do all of them on my own. 
If I may suggest, and if it makes sense to you guys - it seems reasonable to be opened separate issues for each MEMORY command under https://github.com/xetorthio/jedis/issues. In the worst case, you guys will have several issues, maybe labeled `good-first-bug` / `help-wanted`. They may attract more contributors to the awesome project, so it would be a win-win situation. I hope this makes sense.

**Pull request merged**
