### PR TITLE
Provide support for stream api

### PR DESCRIPTION
**Pull request by ninthwang**
When Redis 5.0 released，I started building this branch to support for stream api. Now the testing for MQ has passed, and then will be deployed in the production environment. My modification is based on 2.9 because I need to run in a Java 6 environment

### CODE REVIEW

**Comment by gkorland** [comment]
#1880

**Comment by gkorland** [comment]
@ninthwang any chance to got to look at #1880 ?

**Comment by sazzad16** [comment]
@gkorland Close this PR?

**Comment by ninthwang** [comment]
I have been busy promoting this feature in two projects in the past few months. I'll modify it according to version 3.x. But the encapsulation code that involves me on top of this is also modified, so it will take some time.

**Comment by sazzad16** [comment]
@ninthwang 

First of all, stream is already a part of Jedis. It was first included from #1880. You can review the current code in master.

Secondly, we won't be accepting new feature against `2.9`.

**Comment by ninthwang** [comment]
> @ninthwang
> 
> First of all, stream is already a part of Jedis. It was first included from #1880. You can review the current code in master.
> 
> Secondly, we won't be accepting new feature against `2.9`.

I reviewed the  the current code in master, and will enrich it to meet my needs. 
But how can I get release versions to support my project runtime environment(JAVA6)?  This situation will last at least two years,  and the last supported version is 2.9.

**Comment by sazzad16** [comment]
> I reviewed the the current code in master, and will enrich it to meet my needs.

Thank you for your enthusiasm!

> ... This situation will last at least two years, ...

Sorry about that. Jedis would also have to progress over time.

BTW, good news is you can always build your own Jedis from source codes. Cheers!

**Pull request closed without merging**
