### PR TITLE
squid:S1213 - The members of an interface declaration or class should…

### PR DESCRIPTION
**Pull request by m-ezzat**
This pull request is focused on resolving occurrences of Sonar rule squid:S1213 - The members of an interface declaration or class should appear in a pre-defined order

You can find more information about the issue here: https://dev.eclipse.org/sonar/coding_rules#q=squid:S1213

Please let me know if you have any questions.

M-Ezzat

### CODE REVIEW

**Comment by marcosnils** [comment]
LGTM!

**Comment by HeartSaVioR** [comment]
LGTM

**Comment by HeartSaVioR** [comment]
@marcosnils 
Since it just rearranges fields/methods order, I'm not sure we want to backport this to all branches.

**Comment by marcosnils** [comment]
@HeartSaVioR I like this one. Let's apply from 2.8 onwards, WDYT?

**Comment by HeartSaVioR** [comment]
Good. Please feel free to merge & backport. :)

**Comment by HeartSaVioR** [comment]
Merged into master, 2.8, 2.9 respectively.

**Pull request merged**
