### PR TITLE
Support setting client name from sentinel pool

### PR DESCRIPTION
**Pull request by tgyurci**

### CODE REVIEW

**Comment by marcosnils** [comment]
@tgyurci this change will break backwards compatibility as it changes a current constructor. I guess it's better to create a new constructor with the new field to prevent this situation.

**Comment by tgyurci** [comment]
I have created a new constructor with same arguments and it calls the new one.

**Comment by marcosnils** [comment]
@tgyurci you're right github diff tricked me. 

One another collaborator reviews it we can merge. Thanks for contributing!.

**Comment by HeartSaVioR** [comment]
@tgyurci LGTM. It is already included to JedisPool, so adding it to JedisSentinelPool is totally make sense.

**Comment by HeartSaVioR** [comment]
Thanks @tgyurci for contributing, I merged this to master, 2.7, 2.8 branches respectively.

**Pull request merged**
