### PR TITLE
Bug fix in JedisCluster scan

### LINKED ISSUE #1901: Scan not supporting hash tag
https://github.com/xetorthio/jedis/blob/53194dd03bf397211566ba48a60e9f1e549c85ae/src/main/java/redis/clients/jedis/JedisCluster.java#L1337

Shouldn't there be a NOT (!) sign for this? Looks like this is saying if the matchPattern is cluster compliant, then throw error, whereas it should be otherway.

I'm currently trying to scan for keys with match pattern of "crossing:{123}-*" (without double quotes), and it's throwing the exception from line 1338 of JedisCluster.

### PR DESCRIPTION
**Pull request by sazzad16**
Closes #1901

### CODE REVIEW

**Comment by marcosnils** [comment]
LGTM!>

**Comment by sazzad16** [comment]
Merged into master, 2.10, 2.9.

**Comment by marcosnils** [comment]
Just realize this doesn't have a test. Shouldn't we add one?

**Comment by marcosnils** [comment]
Yes, I've seen those but maybe in this case it's work to add a JedisCluster test specifically to test that condition.

**Pull request merged**
