### PR TITLE
log the error for redirection of request

### PR DESCRIPTION
**Pull request by jiafu1115**
current, when moved/asked happen (such as fail over happen), no any message hint the event. 
so suggest log it as warn to show the event.

test result example:
WARNING: should request to : 127.0.0.1:7380

BTW： the tests are not stable.

### CODE REVIEW

**Comment by sazzad16** [comment]
@jiafu1115 In case of cluster reconfiguration, node repair like scenarios user can be bombarded with this kind of logs. These scenarios may be rare but expected. So, IMHO, we should not log these exceptions.

**Comment by sazzad16** [comment]
@marcosnils WDYT?

**Comment by jiafu1115** [comment]
node repair should only happen in control limit time period. it shouldn't take too much time. Take normal case, for example, I take manual fail over and no any message for the application to know the event. so I raise this PR.

**Comment by sazzad16** [comment]
@marcosnils @HeartSaVioR Close?

**Comment by jiafu1115** [comment]
@sazzad16 change to fine from warning to let user have more choice to decide if track the change.

**Comment by jiafu1115** [comment]
will open new one due to the PR is to older branch.

**Pull request closed without merging**
