### PR TITLE
Removed final modifier from arguments of interfaces

### PR DESCRIPTION
**Pull request by sazzad16**

### CODE REVIEW

**Comment by marcosnils** [comment]
LGTM!. @HeartSaVioR ?

**Comment by HeartSaVioR** [comment]
LGTM. I wasn't aware that adding final to parameter has no effect. Nice finding.

**Comment by HeartSaVioR** [comment]
@sazzad16 
Sorry now this has conflicts between master. Could you rebase your change with latest? Thanks in advance!

@marcosnils 
Since this fixes 'non-effective' thing (I mean nothing changed), do you think we really need to port back to 2.x version line?

**Comment by sazzad16** [comment]
@HeartSaVioR Please check now.

**Comment by sazzad16** [comment]
@HeartSaVioR Rebased. Please check.

**Comment by sazzad16** [comment]
Merged into master, 2.10, 2.9.

**Comment by marcosnils** [comment]
awesome!.

**Pull request merged**
