### PR TITLE
Add two byte array as constants for boolean true/false

### PR DESCRIPTION
**Pull request by itugs**
Introduce two byte array for boolean true and false to avoid to create same byte array repeatedly.

### CODE REVIEW

**Comment by HeartSaVioR** [comment]
@itugs Looks good to me, thanks for your effort!

**Comment by HeartSaVioR** [comment]
@itugs With one more collaborator reviews this PR, PR can be merged.

**Comment by marcosnils** [comment]
LGTM, you can go ahead and merge.

**Comment by HeartSaVioR** [comment]
Merged into master, 2.6, 2.7 branches.
@marcosnils Thanks for reviewing. :)
@itugs Thanks for your effort! I merged your PR.

**Comment by itugs** [comment]
@HeartSaVioR Thanks. This is my first PR, so, wow I'm very happy :-)

**Comment by HeartSaVioR** [comment]
@itugs Oh, that's a great news! Please keep up the good work. :)

**Pull request merged**
