### PR TITLE
Reduce sleep time to resolve test failing issue

### PR DESCRIPTION
**Pull request by sazzad16**
Recent PRs are failing after these lines.

### CODE REVIEW

**Comment by sazzad16** [comment]
@HeartSaVioR @marcosnils I'm applying myself. Hope this is okay.

**Comment by sazzad16** [comment]
@HeartSaVioR @marcosnils

**Comment by marcosnils** [comment]
@sazzad16  wondering why's the reason that reducing the sleep makes it work.

**Comment by sazzad16** [comment]
@marcosnils Your guess is as good as mine.
I played with different combinations of Jedis timeout, sleep time and Redis timeout. This turned out to be the minimal change that worked every the time in travis.

**Comment by marcosnils** [comment]
If this makes tests more reliable then LGTM!

**Comment by sazzad16** [comment]
@marcosnils I won't say this is a _reliable_ fix but more of a _quick_ fix.

Travis builds are failing for all the PRs. I thought it'd be a good idea to have a quick fix. We may create an issue to dig into this.

**Comment by sazzad16** [comment]
From December 12th, 2017, Travis jobs are running in **Trusty** environment. This could be the reason. PRs before this date were passing (1706 and earlier) but PRs after this date are failing (1710 and later).

@marcosnils @HeartSaVioR

**Comment by marcosnils** [comment]
@sazzad16 got it. Let's go ahead and merge this until we find a better fix.

**Comment by sazzad16** [comment]
Merged into master, 2.10.

**Pull request merged**
