### PR TITLE
Throw an exception when trying to read from a broken connection

### PR DESCRIPTION
**Pull request by mina-asham**
- When attempting to read from a broken connection, Jedis could potentially try to read some corrupt data and interpret it according to the Redis protocol, this makes it throw an exception instead of trying that.
- https://github.com/xetorthio/jedis/issues/1747 describes that possible misinterpretations of the protocol can lead to trying to create very large arrays
- Also refactor clientPause test, it was testing that clients fail, CLIENT PAUSE command pauses all clients, so they should be expected to be delayed rather than failed

### CODE REVIEW

**Comment by mina-asham** [comment]
ping, it's quite a small diff...

**Comment by mina-asham** [comment]
Another ping... @marcosnils @gkorland

**Comment by marcosnils** [comment]
LGTM. @smadasu I've changed it to 3.0.2 as it's not adding anything new features.

**Comment by sazzad16** [comment]
@marcosnils Sure!

BTW, It's @sazzad16, not @smadasu ;)

**Comment by suryavtkt** [comment]
what does it mean broken connection, what are the possibilities to broke a connection

**Pull request merged**
