### PR TITLE
JedisClusterCRC16.getSlot() wraps NullPointerException

### PR DESCRIPTION
**Pull request by sazzad16**
- This is similar to SafeEncoder.encode(String).
- This helps JedisClusterCommand specially in case of multi key operations.

Also includes,
- Move CRC16 tests in one place.
- Fix a wrong usage of DEFAULT_REDIRECTIONS.

### CODE REVIEW

**Comment by sazzad16** [comment]
@marcosnils @HeartSaVioR

**Comment by marcosnils** [comment]
LGTM. Can be merged after rebased.

**Comment by sazzad16** [comment]
@marcosnils 3.0.0 is the one to go for. Because

1. Previously, a null key would cause `NullPointerException`. What if people have implementation catching this one?

2. `JedisClusterOperationException` is only available in 3.0.0.

**Comment by marcosnils** [comment]
> Previously, a null key would cause NullPointerException. What if people have implementation catching this one?

This is a bug and shouldn't be thrown. 



> JedisClusterOperationException is only available in 3.0.0.

We can't do anything about this. Let's schedule it for 3.0 then :)

**Comment by sazzad16** [comment]
Merged into master.

**Pull request merged**
