### PR TITLE
Fixes binary compatibility between 2.6.3 and 2.7.x

### PR DESCRIPTION
**Pull request by marcosnils**
This PR fixes issues presented in #1043 where sprint data redis stopped working due to binary compatibility issues. 

@HeartSaVioR @xetorthio this is the last PR needed to release 2.7.3. Plz review and comment

### CODE REVIEW

**Comment by HeartSaVioR** [comment]
LGTM.

**Comment by HeartSaVioR** [comment]
@marcosnils We should apply this to 2.8 branch.

**Comment by marcosnils** [comment]
@HeartSaVioR merged into 2.8 as well!.

**Comment by HeartSaVioR** [comment]
@marcosnils Great! Thanks for the quick fix.

**Pull request merged**
