### PR TITLE
2.7+ping subscribe

### PR DESCRIPTION
**Pull request by Anisotrop**
Expects PONG also as a valid response even in subscribe mode. Basically this should allow a session like the following:

```
telnet localhost 6379
Trying ::1...
telnet: connect to address ::1: Connection refused
Trying 127.0.0.1...
Connected to localhost.
Escape character is '^]'.
subscribe test
*3
$9
subscribe
$4
test
:1
ping
*2
$4
pong
$0

ping
*2
$4
pong
$0

unsubscribe test
*3
$11
unsubscribe
$4
test
:0
```

### CODE REVIEW

**Comment by marcosnils** [comment]
@Anisotrop nice catch. Is there a reason why this shouldn't be merged to master?

**Comment by Anisotrop** [comment]
Thanks @marcosnils, it can go to master of course. The 2.7 was the closest to the release we are using and I needed to be able to test it. Do you need me to create a separate PR for master (eventually other branches) ?

**Comment by marcosnils** [comment]
@Anisotrop yes, please close this PR and open another in master branch. Also please make sure to add a test for your code, if you don't know how reach out so we can help.

Thx again!.

**Comment by marcosnils** [comment]
Dup of #1281

**Pull request closed without merging**
