### PR TITLE
Issue-1126: Make HostAndPort implement Serializable

### PR DESCRIPTION
**Pull request by mjtieman**
Updated HostAndPort to implement Serializable.

### CODE REVIEW

**Comment by HeartSaVioR** [comment]
LGTM

**Comment by marcosnils** [comment]
LGTM

**Comment by mjtieman** [comment]
Is this good to merge?

**Comment by marcosnils** [comment]
Merged to 2.7 and 2.8 respectively. Thanks @mjtieman for the contribution!.

**Pull request merged**
