### PR TITLE
Closes #481

### LINKED ISSUE #481: psetex() and others missing javadoc comments
The Redis command [psetex](http://redis.io/commands/psetex) appears to be missing from the [Jedis API](http://tool.oschina.net/uploads/apidocs/redis/clients/jedis/Jedis.html).

### PR DESCRIPTION
**Pull request by marcosnils**

### CODE REVIEW

**Comment by xetorthio** [comment]
LGTM

**Comment by HeartSaVioR** [comment]
LGTM, too.

**Comment by HeartSaVioR** [comment]
@marcosnils 
Is it complete? #481 points out methods' javadoc are missing, and psetex is one of them.
I'd like to know your plan. If you want to cover only psetex, I'll merge it right now.

**Comment by marcosnils** [comment]
Megamerged to master, 2.7 and 2.8

**Pull request merged**
