### PR TITLE
adding info command with section to pipeline

### LINKED ISSUE #857: Unsupported INFO with Section in Pipeline
Jedis.java has 2 methods for INFO command:
public String info();
public String info(final String section);

but Pipeline.java has just one:
public Response<String> info();

### PR DESCRIPTION
**Pull request by nykolaslima**
closes #857

@marcosnils @psydell

### CODE REVIEW

**Comment by HeartSaVioR** [comment]
LGTM.
It introduces new functionality / API so I've labeled it to 2.7.0.

**Comment by marcosnils** [comment]
:+1:

**Comment by marcosnils** [comment]
Merged to master and 2.7

**Comment by HeartSaVioR** [comment]
@marcosnils Marcos, 2.7 branch seems to reverted. What's up?

**Comment by marcosnils** [comment]
I've tried to merge into 2.7 but for some reason files seem to differ a lot. I'm trying to find why

**Comment by marcosnils** [comment]
@HeartSaVioR think I've found the error. Looks like you've accidentally applied the old formatting to 2.7 in this commit b557f7a2edb0dff5885fd237a713ae89c7d329b1. That's why everything we try to merge through cherry pick now shows conflict because formatting between the two branches are not the same. 

Is there a chance you can take a look at it please?

Thanks!.

**Comment by nykolaslima** [comment]
Hi @marcosnils. This comment is for me? Do you need me to apply any other formatter?

**Comment by marcosnils** [comment]
@nykolaslima the comment is for @HeartSaVioR . Looks like he accidentally reverted the code format in 2.7 when merging some functionality. Let's wait he answers and then decide what to do.

**Comment by nykolaslima** [comment]
Ok, if I can help with something just let me know.

**Comment by HeartSaVioR** [comment]
@marcosnils I found MultiKeyPipelineBase was not formatted properly in b557f7a.
Great! Thanks for follow up.

Btw, to not repeat conflict issues between two formatter, we would be better to apply hbase formatter to current 2.6 / 2.7 branch once again. 
(Do we need to apply it to master again?)

I'd like to hear your opinion.

**Comment by marcosnils** [comment]
@HeartSaVioR It'd be great if we add a `make format` target in the makefile so we can apply formatting easily and fast. That way every time we find a formatting issue we just run that before committing and problem's gone.

**Comment by HeartSaVioR** [comment]
@marcosnils Great! We already have ```mvn java-formatter:format```, but maybe unifying all commands to "make" seems consistent approach.

**Comment by HeartSaVioR** [comment]
Introducing ```make format``` is now in progress at #861.

**Comment by HeartSaVioR** [comment]
@nykolaslima Marcos pushed your effort into 2.7. Thanks again for your effort!

**Comment by nykolaslima** [comment]
@HeartSaVioR @marcosnils  thank you guys!

**Pull request merged**
