### PR TITLE
Tru sphere ssl tls support

### PR DESCRIPTION
**Pull request by marcosnils**

### CODE REVIEW

**Comment by marcosnils** [comment]
This PR follows #1173 with the following changes: 

- Added some basic SSL tests proposed in the previous PR.
- Added travis support to install stunnel and run SSL tests

One important thing to notice is that if Jedis devs don't have stunnel installed Jedis will automatically omit those tests (they will always be executed in the CI env though). The reason for this is because SSL is something that we're wiring into the library and I don't want to force devs to install it in order to run standard Jedis tests (opinions are welcome)

What's I think missing: 

- [ ] Add further tests (Hostname verification validation)
- [ ] Add support for other Jedis stuff like Shard / Cluster / etc?. 

@HeartSaVioR @damiri-ts thoughts?

**Comment by HeartSaVioR** [comment]
@marcosnils 
LGTM. Great for omitting ssl test when not possible!
I agree that we'd be better to add unit test for hostname verification, but I'm curious that we should add all tests for Shard, Cluster with ssl.

**Comment by damiri-ts** [comment]
@marcosnils @HeartSaVioR It looks pretty good. These are the failure mode tests I would add and how I would implement them.
1. Test standard HTTPS hostname verification failure: to do this, simply use "127.0.0.1" instead of "localhost" standard hostname verification should fail because it will complain that "127.0.0.1" does not match the certificate common name of "localhost"
2. Test hostname verification with an explicitly defined hostname verifier: for this one, just create a hostname verifier that expects a hostname other than "localhost".
3. Test certificate trust verification: for this one you can simply not specify a trust store, so that the JVM uses the default trust store, or specify a different trust store that does not contain the stunnel certificate. This should cause a failure to trust the certificate.

These three tests should establish that the standard hostname verification and certificate trust establishment mechanism of the JVM are enforced by the Jedis client. I'm happy to implement these myself if necessary but I get the sense that Marcos may have a desire to work on these so I will defer to him.

**Comment by marcosnils** [comment]
@damiri-ts you've done an amazing job, I'd really like if you can take ownership of the SSL implementation and provide the remaining tests as you've stated in your previous comment. The reason why I close the other PR and opened this one is because I needed to work on top of your original PR and I couldn't submit a PR against your fork because I already have a fork from this repo (this is something that GH should really allow to do somehow). 

Can you please continue the SSL stuff from my jedis fork (https://github.com/marcosnils/jedis) so we can implement the missing stuff on top of this PR?. 

I just wanted to settle the basis so we have a CI env where you can test the SSL stuff and iterate over that. Please don't hesitate to propose new changes or submit PR's as needed. 

@HeartSaVioR when I was referring to ShardedJedis and JedisCluster I was thinking of a way to actually setup SSL connection on those implementation. For what I see in @damiri-ts original PR, SSL was only enabled for standard Jedis object only. 

@damiri-ts Do you mind thinking a proposal to implement SSL on all Jedis variants?

Thanks for all the great work!.

**Comment by damiri-ts** [comment]
@marcosnils Sounds good to me. I'll start working on it tonight. Do I have permission to push to the branch in your fork or should I fork your fork? Or is there a way for me to somehow bring this branch in your fork into my existing fork? This is definitely on the edge of my current knowledge of git.

Thanks for the kind words.

**Comment by marcosnils** [comment]
@damiri-ts I guess the best way to proceed now is if you fork my fork and send the PR's there to the `TruSphere-ssl_tls_support` branch so the reflect here. Once we merge a first version of the SSL support, we can continue working from this repo.

**Comment by damiri-ts** [comment]
@marcosnils GitHub won't let me have two Jedis forks. I'm going to try it this way: https://stackoverflow.com/questions/9153598/how-do-i-fetch-a-branch-on-someone-elses-fork-on-github

**Comment by marcosnils** [comment]
@damiri-ts the best way would be to remove your current fork and re-frok from my fork. That way you can change the code and submit PR's to my work which will be reflected here.

**Comment by marcosnils** [comment]
@damitry-ts can you check the default runc / criu logs folder (/var/run/opencontainer/runc/<container_name>/criu.work) and see why checkpointed failed?

**Comment by HeartSaVioR** [comment]
@damiri-ts @marcosnils 
We don't need to have two forks. Just add marcos' fork to one of remote repo. and fetch, and checkout to marcos' branch.

**Comment by marcosnils** [comment]
@HeartSaVioR but how can he open a PR against my branch if he doesn't fork my fork?

**Comment by HeartSaVioR** [comment]
@marcosnils 
You can even see button of 'pull request' from https://github.com/heartsavior/jedis or other forks.
I don't know exactly how it works, but I assume that Github maintains fork graphs.

**Comment by marcosnils** [comment]
@HeartSaVioR you're right, I didn't notice that. 

@damiri-ts you can just pull my `TruSphere-ssl_tls_support` branch into your fork and then send me the PR so we can continue discussing in this thread

**Comment by damiri-ts** [comment]
@HeartSaVioR @marcosnils Yep, that's what the stackoverflow article I posted earlier on the discussion mentioned. So I have configured Marcos' fork as a remote fork and created a branch off of that.  The git log shows both his and my commits I will then submit that as a separate pull request into Jedis.

@marcosnils I'm not sure I understand the other comment you made. Can you please clarify?

**Comment by marcosnils** [comment]
@damiri-ts you need to submit your PR against my `TruSphere-ssl_tls_support` branch in my jedis fork, that way your commits will be reflected here on this PR

**Comment by damiri-ts** [comment]
@marcosnils OK

**Comment by damiri-ts** [comment]
@marcosnils So I'm trying to create a pull request to your fork but I can't see it as an option in the list of github forks. There are many forks but not yours. Do you think this is a permissions issue?

**Comment by marcosnils** [comment]
@damiri-ts shouldn't be. I can merge the changes manually if you want. To which branch did you push the changes?

**Comment by marcosnils** [comment]
@damiri-ts I can't find your fork: https://github.com/damiri-ts/jedis gives 404

**Comment by damiri-ts** [comment]
@marcosnils https://github.com/trusphere/jedis

**Comment by marcosnils** [comment]
@damiri-ts which branch?

**Comment by damiri-ts** [comment]
@marcosnils ssl_tls_support_with_tests

**Comment by marcosnils** [comment]
@damiri-ts just merged your branch into my fork so it reflects here. I'll review it tomorrow.

**Comment by marcosnils** [comment]
@damiri-ts if I run the complete jedis test suite with `make test` it just hangs. That's why CI reported failed tests. Can you please check?

**Comment by damiri-ts** [comment]
@marcosnils Here's my output from running "make test"

make start
make[1]: Entering directory `/home/damiri/workspaces/jedis/jedis'
rm -vf /tmp/redis_cluster_node*.conf 2>/dev/null
rm dump.rdb appendonly.aof - 2>/dev/null
make[1]: [cleanup] Error 1 (ignored)
echo "$REDIS1_CONF" | redis-server -
echo "$REDIS2_CONF" | redis-server -
echo "$REDIS3_CONF" | redis-server -
echo "$REDIS4_CONF" | redis-server -
echo "$REDIS5_CONF" | redis-server -
echo "$REDIS6_CONF" | redis-server -
echo "$REDIS7_CONF" | redis-server -
echo "$REDIS_SENTINEL1" > /tmp/sentinel1.conf && redis-server /tmp/sentinel1.conf --sentinel
echo "$REDIS_SENTINEL2" > /tmp/sentinel2.conf && redis-server /tmp/sentinel2.conf --sentinel
echo "$REDIS_SENTINEL3" > /tmp/sentinel3.conf && redis-server /tmp/sentinel3.conf --sentinel
echo "$REDIS_SENTINEL4" > /tmp/sentinel4.conf && redis-server /tmp/sentinel4.conf --sentinel
echo "$REDIS_CLUSTER_NODE1_CONF" | redis-server -

*** FATAL CONFIG FILE ERROR ***
Reading the configuration file, at line 3
>>> 'cluster-node-timeout 50'
Bad directive or wrong number of arguments
make[1]: *** [start] Error 1
make[1]: Leaving directory `/home/damiri/workspaces/jedis/jedis'
make: *** [test] Error 2

Could it be I'm not running a recent enough version of the redis-server?

**Comment by marcosnils** [comment]
@damiri-ts yes. You need to download, compile and install the latest redis version from the unstable branch. Here's the link : https://github.com/antirez/redis

**Comment by damiri-ts** [comment]
@marcosnils The problem is somehow with stunnel. If I try to connect to the SSL/TLS port using ```openssl s_client -host localhost -port 6380 -msg```. The server simply doesn't respond.

$ openssl s_client -host localhost -port 6380 -msg
CONNECTED(00000003)
>>> TLS 1.2 Handshake [length 0122], ClientHello
    01 00 01 1e 03 03 56 73 74 a9 ca c5 92 c7 24 3c
    7b 56 c0 87 5b 45 e4 69 ca 4a 63 c8 12 6b 51 4f
    a8 fa cc 3d 75 b3 00 00 88 c0 30 c0 2c c0 28 c0
    24 c0 14 c0 0a 00 a3 00 9f 00 6b 00 6a 00 39 00
    38 00 88 00 87 c0 32 c0 2e c0 2a c0 26 c0 0f c0
    05 00 9d 00 3d 00 35 00 84 c0 12 c0 08 00 16 00
    13 c0 0d c0 03 00 0a c0 2f c0 2b c0 27 c0 23 c0
    13 c0 09 00 a2 00 9e 00 67 00 40 00 33 00 32 00
    9a 00 99 00 45 00 44 c0 31 c0 2d c0 29 c0 25 c0
    0e c0 04 00 9c 00 3c 00 2f 00 96 00 41 c0 11 c0
    07 c0 0c c0 02 00 05 00 04 00 15 00 12 00 09 00
    ff 01 00 00 6d 00 0b 00 04 03 00 01 02 00 0a 00
    34 00 32 00 0e 00 0d 00 19 00 0b 00 0c 00 18 00
    09 00 0a 00 16 00 17 00 08 00 06 00 07 00 14 00
    15 00 04 00 05 00 12 00 13 00 01 00 02 00 03 00
    0f 00 10 00 11 00 23 00 00 00 0d 00 20 00 1e 06
    01 06 02 06 03 05 01 05 02 05 03 04 01 04 02 04
    03 03 01 03 02 03 03 02 01 02 02 02 03 00 0f 00
    01 01

Then it just hangs. This behavior is completely different from the stunnel response when I start it as a service on my linux desktop.

**Comment by damiri-ts** [comment]
@marcosnils OK, I found the issue. I'll push a fix to my branch shortly. Should I squash it with the last commit or will that complicate things when you merge it to your branch?

**Comment by damiri-ts** [comment]
@marcosnils I pushed a fix to my branch ssl_tls_support_with_tests at https://github.com/trusphere/jedis

There are still some tests failures (54) but they are not SSL/TLS tests. I'm guessing it's something missing from my local environment.

**Comment by marcosnils** [comment]
@damiri-ts just merged here. Waiting for CI to finish.

**Comment by marcosnils** [comment]
@damiri-ts things look much better now. I've realized that you added some test features that are only available from java7 onwards and all tests from lower JDK's fail. Is there a chance to omit those features on the tests so we can get test to pass on JDK6+?

**Comment by damiri-ts** [comment]
@marcosnils I could omit those tests but then we wouldn't have any tests for that particular feature. That specific feature is only available in Java7, it allows the user to use the Java HTTPS hostname verifier for non HTTPS SSL/TLS connections. It's a pretty handy feature since otherwise the user has to find or create a HostnameVerifier implementation.

Is there a way to structure the project so that it runs a set of tests only if it is compiled with Java 7?

**Comment by damiri-ts** [comment]
@marcosnils For now, I just commented out the tests that require Java 7. Java 6 is end-of-life so perhaps we can add them back in sometime in the future. Please merge from my branch.

**Comment by marcosnils** [comment]
@HeartSaVioR WDYT?

**Comment by HeartSaVioR** [comment]
@marcosnils Can we drop supporting JDK 6 starting at Jedis 2.9.0? Now is the time we can discuss.

**Comment by damiri-ts** [comment]
@marcosnils @HeartSaVioR Any update on this?

**Comment by marcosnils** [comment]
@damiri-ts PR seems ok. Have you had the change to evaluate how SSL would work for the other Jedis services such as JedisCluster and ShardedJedis?

**Comment by damiri-ts** [comment]
@marcosnils No I have not. I'm still coming up to speed on those aspects of Jedis. I will continue working on those but would appreciate it if we can merge this pull request so that it does not become too stale.

**Comment by marcosnils** [comment]
@damiri-ts I'll go ahead and merge this so we can build further SSL stuff from this.

**Comment by damiri-ts** [comment]
@marcosnils BTW is there a feature tracking system for Jedis? Somewhere where we can define work that needs to be done along with acceptance criteria? Like Jira, Rally, or similar?

**Comment by marcosnils** [comment]
@damiri-ts. No there isn't, we usually open issues here and label them as "Discussion needed" for pending stuff.

**Comment by HeartSaVioR** [comment]
@marcosnils Did you backport this to 2.9 via merge or rebase? `2.9` branch is even with master now, which contains breaking compatibilities.

**Comment by HeartSaVioR** [comment]
Maybe 2.9 branch is based on master. It should be based on 2.8.

**Comment by marcosnils** [comment]
@HeartSaVioR you're correct. I've accidentally created 2.9 based on master. I've already reverted it and downmerged this PR accordingly. 

Thanks for the notice!.

**Comment by HeartSaVioR** [comment]
@marcosnils Great!
@damiri-ts @marcosnils Thanks for the greatwork!

**Comment by marcosnils** [comment]
@damiri-ts I've spoken with @xetorthio about JDK support and we both agree with @HeartSaVioR that we should drop support for older JVM's starting from jedis 3.0 onwards. Can you please open a new PR to add the hostname verification stuff against master?. I've alread removed JDK6 from the CI environment so tests should pass now.

Thx!.

**Comment by damiri-ts** [comment]
@marcosnils @HeartSaVioR I've created the pull request. FYI work is going to be a bit hectic for me for the next week but don't despair I'm will eventually submit SSL/TLS support for ShardedJedis and JedisCluster.

**Comment by marcosnils** [comment]
@damiri-ts thanks again and don't worry, Jedis will be waiting until you come back :smile:

**Comment by marcosnils** [comment]
@HeartSaVioR 2.9 should be correct now, can you please verify?

**Comment by HeartSaVioR** [comment]
@marcosnils Confirmed :) Great work!

**Comment by markthegrea** [comment]
So when will this be ready for prod?  2.9?  i am working with Azure and we need this...!

**Comment by marcosnils** [comment]
@markthegrea the 2.9 branch is prod ready but not released because we're waiting for further stuff before shipping. You can still build the jar from the 2.9 branch and start using ssl today.

**Comment by markthegrea** [comment]
Hate to bother you but when is 2.9 coming out?  We need SSL soon and it is above my skill level to build a jar from a branch with all that entails.  There are other alternatives but would like to stay with Jedis...

**Comment by marcosnils** [comment]
@markthegrea here's how you build Jedis from a branch

```
git clone --branch 2.9 https://github.com/xetorthio/jedis.git
cd jedis && mvn -DskipTests package
```
Your jar will be available in the target directory
enjoy!.

**Comment by markthegrea** [comment]
yes, we could do that but we cannot use the jar we create in our Storm Cluster.  We must get all our jars from Maven directly.

Is there a roadmap?  A date?

**Comment by marcosnils** [comment]
@markthegrea We still need to work in some improvements in 2.8 regarding cluster scenarios. I'm trying to allocate some bandwidth to close those and some pending stuff for 2.9 as well. Hopefully we'll release 2.8.2 and 2.9 by the end of June.

**Comment by HeartSaVioR** [comment]
@markthegrea 
I know it's really bothering but you can still do some trick: 
- Add 'jedis' as dependency with 'provided' scope from your topology
- Copy your jedis jar to extlib directory of each of Storm installation. Please note that you also need to copy commons-pool 2 jar, too.

**Comment by rhuddleston** [comment]
To confirm will ssl be added to 2.8 branch or will this be 2.9+ only?

**Comment by marcosnils** [comment]
2.9 onwards as it's a new feature

sent from mobile

**Pull request merged**
