### PR TITLE
Reset timeout to initial value

### PR DESCRIPTION
**Pull request by sazzad16**
In two test methods, Redis config is changed but is not reset to initial value. Because of this, `redis.clients.jedis.exceptions.JedisConnectionException: Unexpected end of stream.` occurs time to time in tests. This PR will resolve this issue.

### CODE REVIEW

**Comment by sazzad16** [comment]
@HeartSaVioR @marcosnils Please review this. Once timeout is set to 1 second, tests with 1+ seconds of sleep are tend to fail. Resetting timeout should resolve this issue.

**Comment by sazzad16** [comment]
@marcosnils @gkorland Please review this.

**Comment by sazzad16** [comment]
@gkorland Just being lazy, but I think we can use `try-finally` in entire project in separate PR.

**Comment by marcosnils** [comment]
> Just being lazy, but I think we can use `try-finally` in entire project in separate PR.

LGTM!. 

Good catch @sazzad16

**Pull request merged**
