### PR TITLE
zrangeByScore has wrong description for min / max paremeter.

### PR DESCRIPTION
**Pull request by novice81**
Double.MIN_VALUE & Double.MAX_VALUE doesn't work.
They should be Double.NEGATIVE_INIFINITY & Double.POSITIVE_INFINITY.

### CODE REVIEW

**Comment by marcosnils** [comment]
LGTM!

**Comment by HeartSaVioR** [comment]
LGTM. Great finding!

**Comment by HeartSaVioR** [comment]
Merged into master, 2.9, 2.10 respectively.

**Comment by novice81** [comment]
thanks!

**Pull request merged**
