### PR TITLE
add spop with count command available in 3.0

### PR DESCRIPTION
**Pull request by argvk**
hello, 

redis 3.0 adds support for `spop` with a count, this PR adds the same for jedis

http://redis.io/commands/SPOP

thanks

### CODE REVIEW

**Comment by HeartSaVioR** [comment]
Looks good to me, thanks for your effort!
Now waiting for reviewing.

**Comment by marcosnils** [comment]
Looks good, let's merge!.

**Comment by HeartSaVioR** [comment]
Thanks @argvk, I merged into master and 2.7 respectively.

**Comment by argvk** [comment]
Awesome, thanks a lot!!

**Pull request merged**
