### PR TITLE
Fix resource leaks and warnings in Junit tests #1332

### PR DESCRIPTION
**Pull request by smadasu**
FIxed resource leak warnings. Please review

### CODE REVIEW

**Comment by marcosnils** [comment]
@smadasu how / when do you see this warnings?. In your editor?. 

As these are unit tests, it's not super important to do resource cleanup. I'm not sure about this change

@HeartSaVioR @xetorthio ?

**Comment by xetorthio** [comment]
Yeah. They are all on testa, unless I missed something. If that is the case
then I wouldn't worry too much.

**Comment by smadasu** [comment]
Yes. They are all unit tests. It may solve some of the random unit test failures we have seen in the past. But it's up to you guys to merge. This is not a high priority PR.

**Comment by HeartSaVioR** [comment]
@marcosnils @xetorthio 
I like the change though they're just tests. Someone starts from test codes to see the usage patterns, so though they're not critical, but also not bad to change them.

@smadasu 
There're too many inconsistent style issues, whether try after space or not, if after space or not, ( after space or not, and so on. Yes we don't use checkstyle and also don't specify style guideline so you may wonder why I'm saying about style, but even narrowing code to only your changeset, the code style is inconsistent. 

Please have a look at other code blocks and try to keep the code style. We might need to discuss the code style or even set up checkstyle in maven process.

**Comment by marcosnils** [comment]
Closed due to inactivity

**Pull request closed without merging**
